### ISSUE TITLE
Cannot read property 'eachPaneView' of undefined

### ISSUE THREAD

**Issue by vmakhaev** [ahuth/preview-tabs#23]
Atom 1.0

```
TypeError: Cannot read property 'eachPaneView' of undefined
    at new PreviewTabsPanesManager (/Users/vmakhaev/.atom/packages/preview-tabs/lib/preview-tabs-panes-manager.coffee:11:49)
    at Object.module.exports.activate (/Users/vmakhaev/.atom/packages/preview-tabs/lib/preview-tabs.coffee:9:45)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```

**Comment by ahuth** [comment]
Thanks for reporting this! Unfortunately, I'm no longer developing this plugin.

The good news is that Atom has this functionality built in, now, so you don't need a plugin for it! Under the settings for the "tabs" package, there is a checkbox for preview tabs:

![screen shot 2015-06-28 at 7 13 35 am](https://cloud.githubusercontent.com/assets/2503289/8396686/47e66d6e-1d65-11e5-9956-2b11420e6064.png)

**Comment by vmakhaev** [comment]
Thanks for information.
